gcc_command = gcc_cygwin

default:
	$(gcc_command) c_calc_mfi.c -o c_calc_mfi.exe
	$(gcc_command) c_calc_rsi.c -o c_calc_rsi.exe
	$(gcc_command) c_calc_sma.c -o c_calc_sma.exe
	$(gcc_command) c_calc_sma_volume.c -o c_calc_sma_volume.exe
	$(gcc_command) c_calc_volatility.c -o c_calc_volatility.exe
